version: '3'
services:
  wordpress:
    build: ./wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
    volumes:
      - ${PWD}/index.php:/var/www/html/wp-content/plugins/humanitix-event-connector/index.php
      - ${PWD}/wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DEFAULT_AUTH: mysql_native_password
